name: Tests and Coverage

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov coverage codecov
        
    - name: Run tests with coverage
      env:
        PYTHONPATH: ${{ github.workspace }}/src
      run: |
        # Run all implementation tests
        python -m pytest tests/kenneth --cov=src/kenneth
        python -m pytest tests/tien --cov=src/tien
        python -m pytest tests/enhanced --cov=src/enhanced
        coverage combine
        coverage xml
        coverage report
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
        token: ${{ secrets.CODECOV_TOKEN }}